# openapi: 3.1.0
# info:
#   version: 1.0.0
#   title: Contacts book app
#   license:
#     name: Apache 2.0
#     url: http://www.apache.org/licenses/LICENSE-2.0.html
#   description: This is a documentation of conracts app
# tags:
#   - name: Contacts
#     description: Operations about contacts
#     name: Auth
#     description: Auth operations
# servers:
#   - url: http://localhost:3000
#   - url: https://nodejs-hw-mongodb-5yys.onrender.com
# paths:
#  /contacts/{id}:
#     get:
#       $ref: ../swagger/paths/contacts/{id}/get.yaml
# components:
#   securitySchemes:
#     bearerAuth:
#       type: http
#       scheme: bearer

openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: |
    This is the documentation of the Contacts API.
    It includes operations for managing contacts and user authentication.

tags:
  - name: Contacts
    description: Operations related to contacts.
  - name: Auth
    description: Operations related to authentication.

servers:
  - url: https://nodejs-hw-mongodb-5yys.onrender.com
    description: Production server (Render)
  - url: http://localhost:3000
    description: Local development server

paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml

  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
